version: '3.4'
services:
    pruefstelle_setup:
        image: alpine:latest
        volumes:
            - ./database:/mnt/setup
        command: >
            ash -c "touch /mnt/setup/database.db"
        restart: on-failure

    pruefstelle_frontend:
        build:
            context: ./../frontend
            target: deploy-static
        ports:
            - 3000:3000
        volumes:
            - ./settings/nginx/nginx.conf:/etc/nginx/nginx.conf
        restart: always
        # as the environment variables must be present during build time, you can't specify them here

    pruefstelle_backend:
        build:
            context: ./../backend
        ports:
            - 8000:8000
        volumes:
            - ./database/database.db:/code/database.db
        depends_on:
            - pruefstelle_setup
        restart: always
        environment:
            ENV_FOR_PRUEFSTELLE: production # development
            # override .secrets.toml:server.cors.origins or any other variable
            # cf. https://www.dynaconf.com/envvars/
            # pruefstelle_server__cors__origins: http://localhost:3000
