dynaconf_merge = true

#
# Default configuration
#

[default.about]
title = "pruefstelle API"
swagger_ui_parameters = { "operationsSorter" = "method" }
contact = { name = "???", email = "example@example.com" }

[default.frontend]
case_path = "/dashboard/case"

[default.mining_service.paths]
new = "/orders/{workflow}"
status = "/orders/{order_id}"
result_keywords = "/orders/{order_id}/keywords"
result_named_entities = "/orders/{order_id}/named-entities"
result_linked_entities = "/orders/{order_id}/linked_entities"

[default.text_importer.paths]
from_du_key = "/du/{du_key}/"

[default.db]
uri = "sqlite:///database.db"
connect_args = { check_same_thread = false }
echo = false

[default.security]
ALGORITHM = "???"
ACCESS_TOKEN_EXPIRES_SECONDS = 43200

#
# Production configuration
#

[production.frontend]
base_url = "http://localhost:3000"

[production.server]
log_level = "info"
reload = false
cors_origins = ["http://localhost:3000"]
host = "0.0.0.0"
port = "8000"

[production.text_importer]
base_url = "???"
url_scheme = "https"
# Make sure to update this path and add the cert/pem file to settings/
verify = "???"

[production.mining_service]
base_url = "???"
url_scheme = "http"

[production.security]
# openssl rand -hex 32
SECRET_KEY = "???"

[production.db]
# ???

#
# Development configuration
#

[development.db]
echo = true

[development.frontend]
base_url = "http://localhost:3000"

[development.server]
log_level = "debug"
reload = true
cors_origins = ["http://localhost:3000"]
host = "localhost"
port = "8000"

[development.mining_service]
base_url = "http://127.0.0.1:8080"
url_scheme = "http"

[development.text_importer]
base_url = "http://127.0.0.1:8080"
url_scheme = "http"

[development.security]
# openssl rand -hex 32
SECRET_KEY = "???"
