dynaconf_merge = true

[default.db]
uri = "sqlite:///database.db"
connect_args = {check_same_thread=false}
echo = false

[default.security]
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRES_SECONDS = 43200

[default.mail]
sender = "example@example.example"
password = "password"
host = "smtp.host.domain"
port = "465"

[default.about]
contact = {name="Example", email="example@example.example"}

[production.frontend]
base_url = "http://????:3000"

[production.server]
log_level = "error"
reload = false
cors_origins = ["http://s????:3000"]
host = "0.0.0.0"
port = "8000"

[production.text_importer]
base_url = "https://text-importer"
url_scheme = "https"
verify = "/home/user/pruefstelle/pruefstelle/backend/setting/fesad_rest.pem"

[production.security]
SECRET_KEY = "verySecretKey"


[development.populate.testuser]
populate = false
email = "example@example.example"
password = "example@example.example"


[production.mining_service]
base_url = "http://mining-serive"
url_scheme = "http" # "https"

[development.security]
SECRET_KEY = "verySecretKey"