dynaconf_merge = true

#
# Default configuration
#

[default.about]
title = "pruefstelle API"
swagger_ui_parameters = { "operationsSorter" = "method" }
contact = { name = "???", email = "???@???.???" }

[default.db]
uri = "sqlite:///database.db"
connect_args = { check_same_thread = false }
echo = false

[default.security]
ALGORITHM = "???"
ACCESS_TOKEN_EXPIRES_SECONDS = 43200 # ???

#
# Production configuration
#

[production.server]
log_level = "info"
reload = false
cors_origins = ["http://localhost:3000"]
host = "0.0.0.0"
port = "8000"

[production.text_importer]
base_url = "???"

[production.mining_service]
base_url = "???"

[production.security]
# openssl rand -hex 32
SECRET_KEY = "???"

#
# Development configuration
#

[development.db]
echo = true

[development.server]
log_level = "debug"
reload = true
cors_origins = ["http://localhost:3000"]
host = "localhost"
port = "8000"

[development.mining_service]
base_url = "http://127.0.0.1:8080"

[development.text_importer]
base_url = "http://127.0.0.1:8080"

[development.security]
# openssl rand -hex 32
SECRET_KEY = "???"
