dynaconf_merge = true

[default.about]
title = "pruefstelle API"
swagger_ui_parameters = {"operationsSorter"="method"}

[default.frontend]
case_path = "/dashboard/case"

[default.mining_service.paths]
new = "/orders/{workflow}"
status = "/orders/{order_id}"
result_keywords = "/orders/{order_id}/keywords"
result_named_entities = "/orders/{order_id}/named-entities"
result_linked_entities = "/orders/{order_id}/linked_entities"

[default.text_importer.paths]
from_du_key = "/du/{du_key}/"

[production.db]
echo = true

[development.db]
echo = true

[development.server]
log_level = "debug"
reload = true
cors_origins = ["http://localhost:3000"]
host = "localhost"
port = "8000"

[development.frontend]
base_url = "http://localhost:3000"


[development.mining_service]
base_url = "http://127.0.0.1:8080" #
url_scheme = "http" # "https"


[development.text_importer]
base_url = "http://127.0.0.1:8080" #
url_scheme = "http" 